In [23]:
import sys
import os

sys.path.append(os.path.abspath('..'))

In [24]:

import pandas as pd
import numpy as  np
import datetime as dt
import pandas as pd
import numpy as np
import datetime as dt

from Python_arq import engines as engs
from sqlalchemy import text
from calendar import day_name
from sqlalchemy import text
from pathlib import Path

In [25]:
try:
    eng = engs.get_engine()
    text_qry = text(engs.load_query('qry_olos.sql'))
    df = pd.read_sql(text_qry, eng)
except Exception as e:
    print (f'Erro ao executar consulta: {e}')

In [26]:
dia_semana = {
    'Monday': 'Segunda',
    'Tuesday': 'Terça',
    'Wednesday': 'Quarta',
    'Thursday': 'Quinta',
    'Friday': 'Sexta',
    'Saturday': 'Sábado',
    'Sunday': 'Domingo'
}

df['day_week'] = df['data'].apply(lambda x: day_name[x.weekday()]).map(dia_semana)
df['data'] = pd.to_datetime(df['data'])
df['semana_mes'] = (
    df['data'].dt.day.sub(1) // 7 + 1 
)
df['day_week'] = df['day_week'] + '_W' + df['semana_mes'].astype(str)

In [27]:
df.columns

Index(['area', 'base_type', 'campaign_id', 'tablename', 'disposition_nivel_1',
       'data', 'hour', 'tentativas', 'atendidas', 'day_week', 'semana_mes'],
      dtype='object')

In [64]:
df_today = df.copy()
df_today = df_today[df_today['data'] == '2026-05-08']
df_today = df_today.groupby(['tablename']).agg(
    tentativas = ('tentativas','sum'),
    atendidas = ('atendidas','sum')
).reset_index()
df_today['tx'] = ((df_today['atendidas'] /  df_today['tentativas']) * 100 ).round(2)
df_totay = df_today[df_today['tentativas'] > 100]
df_today.sort_values(by='tx',ascending=False)

,tablename,tentativas,atendidas,tx
0,,12,9,75.00
20,_1605_MEDICINA_PAGEVIEW_05052026_V500_pt4,35,3,8.57
1,_1605_ENFERMAGEM_EVENTO_ATUALIZACAOSAUDEMATERN...,658,34,5.17
31,_1605_PSICOLOGIA_EVENTO_SEMINARIOAUTOCUIDADO_0...,22,1,4.55
13,_1605_FISIOTERAPIA_PAGEVIEW_ENGAJADOSMARKETING...,504,20,3.97
3,_1605_ENFERMAGEM_MATERIALRICO_EBOOOK_PROTOCOLO...,27,1,3.70
5,_1605_FISIOTERAPIA_ATIVA_07052026_V500_PT1,27,1,3.70
10,_1605_FISIOTERAPIA_BASELEADS_ENGAJADOSBLACKFRI...,475,17,3.58
11,_1605_FISIOTERAPIA_INATIVO_08052026_V500_pt1,196,7,3.57
19,_1605_MEDICINA_ARTMED_PAGEVIEW_07052026_V500_PT4,198,6,3.03
28,_1605_PSICOLOGIA_EVENTO_IIICONGRESSOONLINEPSIC...,300,9,3.00
14,_1605_MEDICINA_ARTMED_PAGEVIEW_05052026_V500_PT3,466,14,3.00
4,_1605_ENFERMAGEM_MATERIALRICO_EBOOOK_PROTOCOLO...,103,3,2.91
16,_1605_MEDICINA_ARTMED_PAGEVIEW_07052026_V500_PT1,35,1,2.86
12,_1605_FISIOTERAPIA_INATIVO_08052026_V500_pt2,176,5,2.84
25,_1605_PSICOLOGIA_BASELEADS_05052026_V500_pt2,418,11,2.63
8,_1605_FISIOTERAPIA_ATIVA_07052026_V500_PT4,498,12,2.41
23,_1605_NUTRICAO_INATIVO_08052026_V500_PT2,177,4,2.26
35,_1605_PSICOLOGIA_INATIVO_06052026_V500_PT3,185,4,2.16
26,_1605_PSICOLOGIA_BASELEADS_05052026_V500_pt3,331,7,2.11
9,_1605_FISIOTERAPIA_ATIVA_07052026_V500_PT5,198,4,2.02
2,_1605_ENFERMAGEM_INATIVO_06052026_V500_pt3,453,9,1.99
15,_1605_MEDICINA_ARTMED_PAGEVIEW_05052026_V500_PT4,458,9,1.97
33,_1605_PSICOLOGIA_INATIVO_05052026_V500_pt4,255,5,1.96
34,_1605_PSICOLOGIA_INATIVO_06052026_V500_PT2,256,5,1.95
22,_1605_NUTRICAO_INATIVO_08052026_V500_PT1,199,3,1.51
29,_1605_PSICOLOGIA_EVENTO_IIICONGRESSOONLINEPSIC...,277,4,1.44
36,_1605_PSICOLOGIA_PAGEVIEWENGAJADOMARKETING_060...,231,3,1.30
18,_1605_MEDICINA_ARTMED_PAGEVIEW_07052026_V500_PT3,480,6,1.25
7,_1605_FISIOTERAPIA_ATIVA_07052026_V500_PT3,543,6,1.10
37,_1605_PSICOLOGIA_PAGEVIEWENGAJADOMARKETING_060...,218,2,0.92
21,_1605_MULTI_EVENTO_MANGUITOROTADOR_06052026_V694,35,0,0.00
6,_1605_FISIOTERAPIA_ATIVA_07052026_V500_PT2,29,0,0.00
17,_1605_MEDICINA_ARTMED_PAGEVIEW_07052026_V500_PT2,35,0,0.00
27,_1605_PSICOLOGIA_EVENTO_IIICONGRESSOONLINEPSIC...,25,0,0.00
24,_1605_PSICOLOGIA_ATIVA_07052026_V552,101,0,0.00
32,_1605_PSICOLOGIA_INATIVO_05052026_V500_pt3,20,0,0.00
30,_1605_PSICOLOGIA_EVENTO_SEMINARIOAUTOCUIDADO_0...,25,0,0.00

In [29]:
df_tab = df.copy()
df_tab = df_tab[df_tab['data'] == '2026-05-08']
df_tab = df_tab.groupby(['disposition_nivel_1']).agg(
    quantidade = ('disposition_nivel_1','count')
).reset_index()
df_tab.sort_values(by='quantidade',ascending=False)

                        disposition_nivel_1  quantidade
19                                 NoAnswer         142
6                            CarrierMessage         137
1                              Announcement         136
28                                  Silence         120
3                                 BadNumber         108
2                                   BadLine          68
29                           TransferModule          64
12                 IMPRODUTIVO LIGACAO CAIU          60
4                                      Busy          47
24                         RETORNO AGENDADO          38
14            IMPRODUTIVO LIGACAO SEM AUDIO          18
25                 RETORNO OUTRA PLATAFORMA          10
21                      RECUSA NAO INFORMOU          10
10     IMPRODUTIVO DESLIGOU NA APRESENTACAO           9
0                      AbortCustomerOnQueue           5
7                                       FAX           5
22      RECUSA SEM INTERESSE OUTRA FORMACAO           4
26            SEM AFINIDADE FORA DO PUBLICO           4
8       IMPRODUTIVO CAIXA POSTAL NAO ATENDE           4
17                       InternalCongestion           2
11                   IMPRODUTIVO JA E ALUNO           2
5                                CancelDial           1
13             IMPRODUTIVO LIGACAO FALHANDO           1
9                    IMPRODUTIVO DESCONHECE           1
15                IMPRODUTIVO Numero Errado           1
16  IMPRODUTIVO RESPONDEU HSM SEM INTERESSE           1
20                       RECUSA  FINANCEIRO           1
18                  NEGOCIACAO EM ANDAMENTO           1
23         RECUSA SEM TEMPO PARA SE DEDICAR           1
27          SEM AFINIDADE SEM PRE REQUISITO           1