In [8]:
import sys
import os

sys.path.append(os.path.abspath('..'))

In [9]:

import pandas as pd
import numpy as  np
import datetime as dt
import pandas as pd
import numpy as np
import datetime as dt

from Python_arq import engines as engs
from sqlalchemy import text
from calendar import day_name
from sqlalchemy import text
from pathlib import Path


eng = engs.get_engine()
text_qry = text(engs.load_query('qry_olos.sql'))
df = pd.read_sql(text_qry, eng)

Carregando query: qry_olos.sql

OperationalError: (psycopg2.OperationalError) connection to server at "dw-ro.data.grupoa.education" (54.84.45.185), port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
dia_semana = {
    'Monday': 'Segunda',
    'Tuesday': 'Terça',
    'Wednesday': 'Quarta',
    'Thursday': 'Quinta',
    'Friday': 'Sexta',
    'Saturday': 'Sábado',
    'Sunday': 'Domingo'
}

df['day_week'] = df['data'].apply(lambda x: day_name[x.weekday()]).map(dia_semana)
df['data'] = pd.to_datetime(df['data'])
df['semana_mes'] = (
    df['data'].dt.day.sub(1) // 7 + 1 
)
df['day_week'] = df['day_week'] + '_W' + df['semana_mes'].astype(str)

In [ ]:
## performance bases | Hoje ## 
df_today = df[df['data'].dt.date == dt.datetime.today().date()]
df_today = df_today.groupby(['area','base_type']).agg(
    Total_tentativas = ('tentativas','sum'),
    total_atendidas = ('atendidas','sum')
).reset_index()
df_today['performance'] = (df_today['total_atendidas'] / df_today['Total_tentativas'] * 100).round(2)
df_today = df_today.sort_values('performance', ascending=False)
df_today

          area base_type  Total_tentativas  total_atendidas  performance
5     Nutrição    evento              1152               39         3.39
8  Veterinária   inativa               406                8         1.97
7   Psicologia     ativa               533               10         1.88
6    Pediatria     ativa               878               15         1.71
0   Enfermagem     ativa               615                9         1.46
4     Medicina   inativa               694                9         1.30
3     Medicina     ativa              3131               38         1.21
1   Enfermagem   inativa              1001                8         0.80
2     Medicina  Carrinho               645                3         0.47

In [ ]:
## top10 bases ## 
df_top10 = df.groupby(['area','base_type']).agg(
    total_tentativas = ('tentativas','sum'),
    total_atendidas = ('atendidas','sum')
).reset_index()
df_top10['performance'] = (df_top10['total_atendidas'] / df_top10['total_tentativas'] * 100).round(2)
df_top10 = df_top10.sort_values('performance', ascending=False).head(10)
df_top10

           area      base_type  total_tentativas  total_atendidas  performance
57  Veterinária          ativa                58                6        10.34
25        Multi       Carrinho                66                5         7.58
55  Veterinária     Base Leads              3479              214         6.15
60  Veterinária         legado               167                9         5.39
30        Multi         legado                64                3         4.69
31     Nutrição     Base Leads              5716              257         4.50
28        Multi         evento             10897              467         4.29
26        Multi  Material Rico              3556              149         4.19
36    Pediatria     Base Leads              3153              131         4.15
40    Pediatria         evento              4805              189         3.93

In [ ]:
## performance bases | D-1 ## 
d_1 = '2026-04-01'
df_ontem = df[df['data'].dt.date == d_1.date()]
df_ontem = df_ontem.groupby(['area','base_type','tablename']).agg(
    Total_tentativas = ('tentativas','sum'),
    total_atendidas = ('atendidas','sum')
).reset_index()
df_ontem['performance'] = (df_ontem['total_atendidas'] / df_ontem['Total_tentativas'] * 100).round(2)
df_ontem = df_ontem.sort_values('performance', ascending=False)
df_ontem

AttributeError: 'str' object has no attribute 'date'